using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DXApplication4
{
    //public delegate void sel_tab(object s, EventArgs e);
    public delegate void sel_tab0();
    class Globals
    {
        public static sel_tab0 select_taby;
        public static sel_tab0 select_taby1;
        public static sel_tab0 select_taby2;
        public static sel_tab0 select_taby3;
        public static sel_tab0 setFocus1;
        public static int idUser;
        public static string nameUser;
        public static string tDivision;
        public static int access;
        public static string login;
        public static string pass;
        public static string pochta;
        public static string status;
        public static string doljnost;
        public static string note;
        public static int tDivision1;
        public static int zavis;
        public static int idps35;
        public static int idtp;
        public static string nametp;
        public static string mosh;
        public static string marka;
        public static String naspunkt4;
        public static int idvl;
        public static string nameps;
        public static string namevl;
        public static int prich_otkl;
        public static int prich_otkl_det;
        public static string name_prich_otkl_det;
        public static int vidpovrel;
        public static int idvidpovreldetal;
        public static string nazvpovreldetal;
        public static int idprichotkldetal;
        public static string nazvprichotkldetal;
        public static int idpovreldetal;
        public static string imyavpovreldetal;
        public static int id04;
        public static string tp04;
        public static DateTime sdata;
        public static DateTime podata;
        public static string prich04;
        public static string vidotkl04;
        public static Double? protkab04;
        public static int? kolpovrel04;
        public static string vidpovrel04;
        public static Decimal? stoimrem04;
        public static int idprich04;
        public static int idpovrel04;
        public static int idtp04;
        public static int idvidotkl04;
        public static int id610zayavka;
        public static int idfidera;
        public static string nazvfidera;
        public static int idpods;
        public static string nazvpods;
        public static Double? protvl;
        public static DateTime? datavkl06;
        public static DateTime? dataotkl06;
        public static int idvidotkl;
        public static string nazvvidotkl;
        public static int kolotkl;
        public static Double? sumotkltp;
        public static Double? nedootpusk;
        public static int prichotkl6;
        public static String nazprichotkl6;
        public static int rabrza;
        public static String nazvrabrza;
        public static int povrel6;
        public static String nazpovrel6;
        public static int kolpovrel6;
        public static String naspunkt;
        public static Decimal? stoimrem06;
        public static int del;
        public static String clishet;
        public static String cfio;
        public static String cadress1;
        public static String cadress2;
        public static String ctp;
        public static Decimal cdebet;
        public static Decimal cpenya;
        public static Decimal cakt;
        public static String czavnom;
        public static int cidmarka;
        public static String abonshet;
        public static int craion;
        public static String cpotreb;
        public static String cabon;
        public static String uptp;
        public static DateTime updataotkl;
        public static String uplishet;
        public static String upfio;
        public static String upadress1;
        public static String upadress2;
        public static String upnote;
        public static String uptel;
        public static DateTime? umdatavkl;
        public static String fname;
        public static String ndirectory;
        public static String tel_number;
        public static String jraion;
        public static String jfio;
        public static String jadres;
        public static String jkontakty;
        public static String jprichina;
        public static String jotvet;
        public static String jvopros;
        public static int jid;
        public static int jotmena;
        public static DateTime jdata;
        public static String addnew;
        public static int region;
        public static int raion_prom;
       
        public static String tip_shetchika;


    }
}
